### PR TITLE
v1.3.1 (#16)

### PR DESCRIPTION
**Pull request by Conjuro**
- v1.3.1 of Streamlink Twitch GUI
- Updated link to changelog

Attached [.nupkg file](https://github.com/streamlink/streamlink-twitch-gui-chocolatey/files/1036474/streamlink-twitch-gui.1.3.1.zip) renamed to .zip extension.

### CODE REVIEW

**Comment by scowalt** [comment]
To speed up this process in the future, I would love to add you as a maintainer to the chocolatey package and the chocolatey package source.

@Conjuro, can you create an account on chocolatey and respond back with your username so I can add you as a maintainer?

@gravyboat, can we add @Conjuro to the @streamlink/chocolatey-package team? (I can also manually add Conjuro to the collaborators of each repository if you prefer)

For now, I'll go ahead and upload this to chocolatey. Thanks!

**Comment by gravyboat** [comment]
@scowalt If they want to be added we can definitely do so. Let me know. You're an admin on the chocolatey team @scowalt so I believe you can add users as well.

**Comment by Conjuro** [comment]
Sure, happy to be of assistance. My username is the same on both sites, "Conjuro".

**Comment by scowalt** [comment]
@gravyboat, I can only add people to the team if they are already a member of the organization. Are you okay with adding @Conjuro to the organization? If not, I can probably just add a repo collaborator to each repo.

@Conjuro, you're now a maintainer on both chocolatey packages (pending some sort of approval process). Please keep the same workflow we've had going (keep a pending pull request until the package is approved, then merge in). Otherwise, feel free to upload the packages yourself if I haven't gotten around to it. Thanks for your help!

**Comment by gravyboat** [comment]
@scowalt I've sent @Conjuro an invite to the chocolatey team which will take care of both repos.

**Comment by Conjuro** [comment]
@gravyboat Received and accepted. Thank you.

@scowalt Looks good. I've reviewed Chocolatey documentation and believe I understand the process. I'll stick to version changes, emulate the workflow you've used in the past, and leave any major stuff/changes to you.

Package has been approved, so I'll merge and close this PR now.

**Pull request merged**
