### PR TITLE
Livestreamer Twitch GUI deprecation package

### PR DESCRIPTION
**Pull request by scowalt**
@bastimeyer is there anything in particular you want in the description here? Otherwise I'll go ahead and deprecate the Livestreamer Twitch GUI chocolatey package by publishing this package.

### CODE REVIEW

**Comment by bastimeyer** [comment]
No, there doesn't need to be anything special. Could you please change the streamlink-twitch-gui dependency to `>=1.0.0` (or the way chocolatey handles this), so that all future updates are already included? Despite that, everything's okay.
Thanks!

Btw, `1.0.1` is out 😃

**Comment by scowalt** [comment]
According to https://docs.nuget.org/ndocs/create-packages/dependency-versions#version-ranges, listing the version in the way will give us `>=1.0.0`.

I'm working on 1.0.1 now 👍

**Comment by scowalt** [comment]
Actually, re-reading this source, looks like we need:

```
(,1.0]
x ≤ 1.0
Maximum version, inclusive
````

**Comment by bastimeyer** [comment]
They're using interval notation (for whatever reason, which is actually stupid)...
Shouldn't this be `1.0.0` (implicit) or `[1.0.0,)` (explicit)?

**Comment by scowalt** [comment]
You're right, I got a bit confused.

I'll switch back to the implicit notation.

**Comment by scowalt** [comment]
Package submitted and PR will be pulled in when the package is published. https://chocolatey.org/packages/livestreamer-twitch-gui/1.0.0

**Pull request merged**
